usr/share/scim/tables/Amharic.bin
usr/share/scim/icons/Amharic.png

usr/share/scim/tables/Arabic.bin
usr/share/scim/icons/Arabic.png

usr/share/scim/tables/Nepali_Rom.bin
usr/share/scim/tables/Nepali_Trad.bin
usr/share/scim/icons/Nepali.png

usr/share/scim/tables/Thai.bin
usr/share/scim/icons/Thai.png

usr/share/scim/tables/Viqr.bin
usr/share/scim/icons/Viqr.png

usr/share/scim/tables/Yawerty.bin
usr/share/scim/icons/Yawerty.png

usr/share/scim/tables/Bengali-inscript.bin
usr/share/scim/icons/Bengali-inscript.png
usr/share/scim/tables/Bengali-probhat.bin
usr/share/scim/icons/Bengali-probhat.png

usr/share/scim/tables/Gujarati-inscript.bin
usr/share/scim/icons/Gujarati-inscript.png
usr/share/scim/tables/Gujarati-phonetic.bin
usr/share/scim/icons/Gujarati-phonetic.png

usr/share/scim/tables/Hindi-inscript.bin
usr/share/scim/icons/Hindi-inscript.png
usr/share/scim/tables/Hindi-phonetic.bin
usr/share/scim/icons/Hindi-phonetic.png

usr/share/scim/tables/Kannada-inscript.bin
usr/share/scim/icons/Kannada-inscript.png
usr/share/scim/tables/Kannada-kgp.bin
usr/share/scim/icons/Kannada-kgp.png

usr/share/scim/tables/Malayalam-inscript.bin
usr/share/scim/icons/Malayalam-inscript.png

usr/share/scim/tables/Punjabi-inscript.bin
usr/share/scim/icons/Punjabi-inscript.png
usr/share/scim/tables/Punjabi-jhelum.bin
usr/share/scim/icons/Punjabi-jhelum.png
usr/share/scim/tables/Punjabi-phonetic.bin
usr/share/scim/icons/Punjabi-phonetic.png

usr/share/scim/tables/Tamil-inscript.bin
usr/share/scim/icons/Tamil-inscript.png
usr/share/scim/tables/Tamil-phonetic.bin
usr/share/scim/icons/Tamil-phonetic.png

usr/share/scim/tables/Telugu-inscript.bin
usr/share/scim/icons/Telugu-inscript.png

usr/share/scim/tables/LaTeX.bin
usr/share/scim/icons/LaTeX.png
usr/share/scim/tables/IPA-X-SAMPA.bin
usr/share/scim/icons/IPA-X-SAMPA.png
